const fakeData = [
  { img: "https://imgur.com/oXzWlKb.png", category: "Give a seminar on driving safety." },
  { img: "https://imgur.com/KKSPJbT.png", category: "Foster a shelter animal" },
  { img: "https://imgur.com/H971jKR.png", category: "Babysit during PTA meetings." },
  { img: "https://imgur.com/MxcneL3.png", category: "Build birdhouses for your neighbors." },
  { img: "https://imgur.com/ZCsfZtt.png", category: "Clean water for children" },
  { img: "https://imgur.com/Q3D72V1.png", category: "Child Support" },
  { img: "https://imgur.com/G6KzU8j.png", category: "Give IT help to local adults" },
  { img: "https://imgur.com/pNGls1U.png", category: "Clean up your local park." },
  { img: "https://imgur.com/w5SHuqo.png", category: "Food Charity" },
  { img: "https://imgur.com/PcLwVP1.png", category: "Good education" },
  { img: "https://imgur.com/I59p1zi.png", category: "Host a clothing swap." },
  { img: "https://imgur.com/SPvCVbp.png", category: "Organize books at the library." },
  { img: "https://imgur.com/Y1ngO6w.png", category: "Give free music lessons." },
  { img: "https://imgur.com/gvMTF0U.png", category: "Refuge shelter" },
  { img: "https://imgur.com/PGJsMBy.png", category: "Teach people how to register to vote." },
  { img: "https://imgur.com/R5uGr6a.png", category: "Collect stuffed animals." },
  { img: "https://imgur.com/QVTogU8.png", category: "Host a study group." },
  { img: "https://imgur.com/UMKhLnJ.png", category: "Host a river clean-up." },
  { img: "https://imgur.com/A3ckMBf.png", category: "Collect school supplies." },
  { img: "https://imgur.com/A3ckMBf.png", category: "Collect school supplies." },
  { img: "https://imgur.com/Hqu2aye.png", category: "New books for children" },
];
export default fakeData;
